# Generated by Django 3.1.5 on 2021-04-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_sarm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
