# Generated by Django 3.1.5 on 2021-05-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210414_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sarm',
        ),
    ]
